### ISSUE TITLE
Support targets with the same key

### ISSUE THREAD

**Issue by CryoCodec** [cert-manager/trust#29]
Hi Folks, 

I played around a bit and ran into an error when using targets with the same key. Unless there's a way, that satisfies the use case, I find it somewhat limiting. 
Let's take the following example: 

I want to distribute the root ca bundle for the webhooks in linkerd: 
```yaml 
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-webhook-trust-roots
spec:
  sources:
    - secret:
        name: "linkerd-webhook-trust-roots"
        key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
```

Also, I want to distribute the root ca bundle for the linkerd trust anchor: 
```yaml 
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
    - secret:
        name: "linkerd-identity-trust-roots"
        key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
```

This fails with `admission webhook "trust.cert-manager.io" denied the request: spec.target.configMap.key: Invalid value: "ca-bundle.crt": cannot use the same target as another Bundle "linkerd-identity-trust-roots"`. 

Is there a specific reason for not supporting that kind of behaviour?
