### ISSUE TITLE
Support CRDs as target

### ISSUE THREAD

**Issue by sbueringer** [cert-manager/trust#33]
It would be great if it would be possible to use CRDs (with a configurable path) as targets.

For more details please see: https://github.com/cert-manager/cert-manager/issues/5073

We discussed this in the cert-manager meeting and the idea was to potentially make this possible via cert-manager/trust. (and that it's not a good fit for cainjector)

**Comment by erikgb** [comment]
I think this could be a useful feature. Do you have any ideas about how it might be implemented, @sbueringer? I'm mostly interested in the required API changes. 🙌 

/remove-lifecycle stale

**Comment by sbueringer** [comment]
No, no idea. Created this issue a while ago and don't remember any context apart from the issue description above :)

**Comment by erikgb** [comment]
With an improved target resource API in place, ref. https://github.com/cert-manager/trust-manager/issues/243, I think this should be possible to implement.

It could look like this, maybe? 

````yaml
target:
  configMap:
    - format: jks
      key: bundle.jks
      password: whatever
  secret:
    # PEM is the default format
    - key: bundle.pem
  object:
    group: runtime.cluster.x-k8s.io
    version: v1alpha1 # Could be optional and default to v1
    resource: extensionconfigs
    name: test-runtime-sdk-extensionconfig
    jsonPath: /spec/clientConfig/caBundle
````
