### ISSUE TITLE
Support injection pem into an existing configmap

### ISSUE THREAD

**Issue by bakito** [cert-manager/trust#58]
It would be great if it was supported to have certificates injected into existing ConfigMaps if they are annotated, similar to the approach that ist available in OpenShift https://docs.openshift.com/container-platform/4.11/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki

Something like the snippet belo would inject the bundle to configmaps with the provided annotation.
```
target:
  configMapAnnotation:
    trust.https://cert-manager.io/inject-bundle: "true"
```

**Comment by erikgb** [comment]
I like this idea and would love to see it implemented. Suggesting a small adjustment to the proposed API:

```yaml
spec:
  target:
    configMapSelector:
      my-label-key: my-label-value
```

The type of the selector should be `map[string]string` as any other Kubernetes label selector.

**Comment by erikgb** [comment]
I have a suggestion to the UX here, which I think can increase the usability/flexibility. What do you think of just having a well-known annotation/label key that you could add to any configmap or secret. Assuming the name of the trust-manager Bundle is `my-ca-bundle`, this could be as easy as:

````yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    trust.cert-manager.io/inject-bundle: my-ca-bundle
  name: ca-inject 
  namespace: apache
````
